const flowers = [
  {
    id: 1,
    name: "Qizil Atirgul Buketi",
    description:
      "Sevgi va ehtiros ramzi bo‘lgan nafis qizil atirgullar to‘plami.",
    category: "Romantik",
    price: 150000,
    rating: 4.9,
    count: 120,
    colors: ["qizil"],
    image: "/img/qizil-atirgul.png",
    liked: false,
  },
  {
    id: 2,
    name: "Oq Liliya Guldastasi",
    description: "Tozalik va poklikni ifodalovchi nafis oq liliyalar.",
    category: "Elegant",
    price: 180000,
    rating: 4.8,
    count: 85,
    colors: ["oq"],
    image: "/img/oq-liliya.jpg",
    liked: false,
  },
  {
    id: 3,
    name: "Pushti Pionlar",
    description: "Nozik va romantik kayfiyat beruvchi pushti pion gullari.",
    category: "Premium",
    price: 210000,
    rating: 5.0,
    count: 60,
    colors: ["pushti"],
    image: "/img/pushti-pion.jpg",
    liked: false,
  },
  {
    id: 4,
    name: "Aralash Bahor Guldastasi",
    description:
      "Bahorning eng chiroyli gullaridan tuzilgan rang-barang buket.",
    category: "Universal",
    price: 130000,
    rating: 4.7,
    count: 140,
    colors: ["qizil", "sariq", "pushti"],
    image: "/img/bahor.png",
    liked: false,
  },
  {
    id: 5,
    name: "Sariq Lola Buketi",
    description: "Quvonch va iliqlik ulashuvchi yorqin sariq lolalar.",
    category: "Do‘stlik",
    price: 110000,
    rating: 4.6,
    count: 95,
    colors: ["sariq"],
    image: "/img/sariq-lola.webp",
    liked: false,
  },
  {
    id: 6,
    name: "Orxideya Premium",
    description: "Hashamatli va eksklyuziv ko‘rinishga ega orxideya guli.",
    category: "Luxury",
    price: 250000,
    rating: 5.0,
    count: 40,
    colors: ["oq", "pushti"],
    image: "/img/orhideya-miks.jpg",
    liked: false,
  },
];
